name: "Protocol Buffer Go Stubs Generation"
on:
  push:
    tags:
      - v**  # Trigger on version tags (e.g., v1.0.0)

jobs:
  protoc:
    name: "Generate"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service: ["order" , "payment", "shipping"]  
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Ensure compatibility with Node.js 20

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.23.3  # Use the mod version of Go

      - name: Extract Release Version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      - name: "Generate for Golang"
        shell: bash
        run: |
          chmod +x "${GITHUB_WORKSPACE}/run.sh"
          ./run.sh ${{ matrix.service }} ${{ env.RELEASE_VERSION }}
